/**
 * Helpers for The River (New Edition / C2 River I).
 *
 * The River is a one-ended stack: the source is placed first, the remaining
 * river tiles are placed in order, and the lake is the final tile. A river
 * tile must extend the current open end; it may not create a second branch or
 * reconnect to an earlier river segment.
 */

const CARDINALS = ['N', 'E', 'S', 'W'];
const OPPOSITE = { N: 'S', E: 'W', S: 'N', W: 'E' };
const DELTA = {
  N: { x: 0, y: -1 },
  E: { x: 1, y: 0 },
  S: { x: 0, y: 1 },
  W: { x: -1, y: 0 },
};

export function rotateRiverDirections(tileDef, rotation = 0) {
  if (!tileDef?.river?.directions) return [];
  return tileDef.river.directions.map((direction) => {
    const index = CARDINALS.indexOf(direction);
    return CARDINALS[(index + rotation) % CARDINALS.length];
  });
}

export function getRiverNeighborPosition(x, y, direction) {
  return {
    x: x + DELTA[direction].x,
    y: y + DELTA[direction].y,
  };
}

function hasPlacedTileAt(placedTiles, x, y) {
  return placedTiles.some((tile) => tile.x === x && tile.y === y);
}

function getTileAt(placedTiles, x, y) {
  return placedTiles.find((tile) => tile.x === x && tile.y === y);
}

/**
 * Return every legal (x, y, rotation) for the next river tile.
 *
 * @param {object} tileDef candidate river tile
 * @param {object[]} placedTiles placed tiles
 * @param {number} tailIndex index of the current river tail
 * @returns {Array<{x:number,y:number,rotation:number}>}
 */
export function getValidRiverPlacements(tileDef, placedTiles, tailIndex, openDirection) {
  if (!tileDef?.river || tailIndex == null) return [];
  const tail = placedTiles[tailIndex];
  if (!tail?.tile?.river || !openDirection) return [];
  const candidates = [];
  const tailDirections = [openDirection];

  // The game stores the one currently open endpoint explicitly. This is
  // important: River I is a single chain, not a branching river network.
  for (const tailDirection of tailDirections) {
    const position = getRiverNeighborPosition(tail.x, tail.y, tailDirection);
    if (hasPlacedTileAt(placedTiles, position.x, position.y)) continue;

    const requiredEntry = OPPOSITE[tailDirection];
    for (let rotation = 0; rotation < 4; rotation += 1) {
      const candidateDirections = rotateRiverDirections(tileDef, rotation);
      if (!candidateDirections.includes(requiredEntry)) continue;

      // A candidate may not create a second connection to a previously placed
      // tile. This prevents loops and the immediate U-turn patterns described
      // in the official River clarification.
      const otherDirections = candidateDirections.filter((d) => d !== requiredEntry);
      const createsLoopOrBranch = otherDirections.some((direction) => {
        const neighbor = getRiverNeighborPosition(position.x, position.y, direction);
        const existing = getTileAt(placedTiles, neighbor.x, neighbor.y);
        return Boolean(existing?.tile?.river);
      });
      if (createsLoopOrBranch) continue;

      // Official Carcassonne River rule: the river must flow continuously outward
      // from the Source (0,0) and cannot bend back toward the start or previous
      // segments in a U-turn or returning loop. We enforce that the candidate
      // tile's position must be strictly further in bounding distance from the source
      // or maintain an outward progression without folding back.
      const sourceTile = placedTiles[0];
      if (sourceTile && sourceTile.tile?.river?.isSource) {
        // Prevent immediate U-turn back toward the tile we just came from or toward the source
        const entryDirection = OPPOSITE[tailDirection];
        const otherDirections = candidateDirections.filter((d) => d !== entryDirection);
        const pointsTowardSource = otherDirections.some((d) => {
          const neighbor = getRiverNeighborPosition(position.x, position.y, d);
          return neighbor.x === sourceTile.x && neighbor.y === sourceTile.y;
        });
        if (pointsTowardSource) continue;
      }

      // The lake must close the river, so it is only valid as the final tile.
      candidates.push({ x: position.x, y: position.y, rotation, tailDirection });
    }
  }

  return candidates;
}

/**
 * Filter ordinary TilePlacement results down to the official River endpoint.
 * Keeping the normal result shape means meeple options on cities, roads,
 * fields, and cloisters continue to be generated by the existing placement
 * engine.
 */
function isMatchingPlacement(x, y, rotation, candidates) {
  return candidates.some(
    (c) => c.x === x && c.y === y && c.rotation === rotation,
  );
}

export function filterRiverPlacements(validPlacements, riverPlacements) {
  return validPlacements.filter((placement) => 
    placement.rotations.some((rot) => isMatchingPlacement(placement.x, placement.y, rot.rotation, riverPlacements))
  ).map((placement) => ({
    ...placement,
    rotations: placement.rotations.filter((rot) => 
      isMatchingPlacement(placement.x, placement.y, rot.rotation, riverPlacements)
    ),
  }));
}

export function isValidRiverPlacement(tileDef, placedTiles, tailIndex, openDirection, x, y, rotation) {
  return getValidRiverPlacements(tileDef, placedTiles, tailIndex, openDirection).some(
    (candidate) => candidate.x === x && candidate.y === y && candidate.rotation === rotation,
  );
}

export function isRiverComplete(tileDef) {
  return Boolean(tileDef?.river?.isLake);
}

export { CARDINALS, OPPOSITE };
